<?xml version="1.0" encoding="utf-8"?>
<Database Name="SimpleTasks" EntityNamespace="Ext.Net.Examples.SimpleTasks" ContextNamespace="Ext.Net.Examples.SimpleTasks" Class="SimpleTasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SimpleTasksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsFolder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Category_Category" Member="Categories" ThisKey="ID" OtherKey="ParentID" Type="Category" />
      <Association Name="Category_Task" Member="Tasks" ThisKey="ID" OtherKey="CategoryID" Type="Task" />
      <Association Name="Category_Category" Member="ParentCategory" ThisKey="ParentID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Task" Member="Tasks">
    <Type Name="Task">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CompletedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Reminder" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Category_Task" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="IsListParent" Method="IsListParent" IsComposable="true">
    <Parameter Name="targetNode" Type="System.Int32" DbType="Int" />
    <Parameter Name="dropNode" Type="System.Int32" DbType="Int" />
    <Return Type="System.Boolean" />
  </Function>
  <Function Name="Reset" Method="Reset">
    <Return Type="System.Int32" />
  </Function>
</Database>