name: "Deploy Examples Explorer v5 (aspx only)"

on:
  push:
    branches: [ master ]
jobs:
  publish:
    name: "Deploy examples explorer to websites"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Deploy Examples Explorer to https://examples5.ext.net/
      uses: objectdotnet/action-ftp-deploy-then-slack-notification@0.3.0
      with:
        repo-root: src
        ftp-host: ${{ secrets.iis_ftp_host }}
        ftp-user: ${{ secrets.iis_ftp_user }}
        ftp-pass: ${{ secrets.iis_ftp_pass }}
        ftp-root: examples5.ext.net
        slack-webhook:  ${{ secrets.SLACK_WEBHOOK }}
        slack-nick: "Examples Explorer Deploy Service"
        slack-icon: ":extglow:"
